#!/usr/bin/env python3
"""Exact audit for C-PHOTON-SIGNED-SIMPLE-CYCLE-XI-N.

PUBLIC, NON-CANONICAL. Standard library only.
Author: A. M. Thorn <thorn@twistj.com>
License: Apache-2.0.

The general all-volume proof is written in README.md after execution.
This verifier audits exact arithmetic and finite cycle instances only.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import product


def primitive_constants():
    a = Fraction(15625, 177147)
    r = Fraction(41, 25)
    tau = Fraction(73, 70)

    A = 2 * r * a * tau
    q = a * (1 + 6 * r) * tau
    A0 = 2 * r * a
    q0 = a * (1 + 6 * r)

    assert A == Fraction(374125, 1240029)
    assert q == Fraction(2472875, 2480058)
    assert A0 == Fraction(51250, 177147)
    assert q0 == Fraction(169375, 177147)
    assert 0 < q0 < 1
    assert 0 < q < 1
    print(f"CONSTANTS PASS A={A} q={q} A0={A0} q0={q0}")
    return A, q, A0, q0


def S3(q: Fraction) -> Fraction:
    return (1 + 4 * q + q * q) / (1 - q) ** 4 - 1 - 8 * q - 27 * q * q


def series_identity_audit(q: Fraction) -> None:
    s = S3(q)
    assert s > 0
    # Algebraic clearing of denominators for the tail identity.
    lhs = (1 - q) ** 4 * (s + 1 + 8 * q + 27 * q * q)
    rhs = 1 + 4 * q + q * q
    assert lhs == rhs

    # Independent finite recurrence audit: coefficients generated by
    # (1-q)^(-4) reproduce m^3 through a finite exact window.
    # (1-q)^(-4) coefficient at q^k is C(k+3,3).
    from math import comb
    coeff = []
    for m in range(1, 21):
        # coefficient of q^(m-1) in (1+4q+q^2)/(1-q)^4
        k = m - 1
        val = comb(k + 3, 3)
        if k >= 1:
            val += 4 * comb(k + 2, 3)
        if k >= 2:
            val += comb(k + 1, 3)
        coeff.append(val)
        assert val == m**3
    print("SERIES_IDENTITY PASS coefficients_m1_to_20=cubes")


Step = tuple[int, int]
Point = tuple[int, int]


STEPS: tuple[Step, ...] = ((1, 0), (-1, 0), (0, 1), (0, -1))


def add(p: Point, s: Step) -> Point:
    return p[0] + s[0], p[1] + s[1]


def canonical_cycle(vertices: tuple[Point, ...]) -> tuple[Point, ...]:
    """Canonicalize a simple cycle modulo cyclic start, reversal, translation."""
    n = len(vertices)
    candidates = []
    for seq in (vertices, tuple(reversed(vertices))):
        for k in range(n):
            rot = seq[k:] + seq[:k]
            ox, oy = rot[0]
            norm = tuple((x - ox, y - oy) for x, y in rot)
            candidates.append(norm)
    return min(candidates)


def enumerate_simple_cycles(max_len: int = 12) -> dict[int, set[tuple[Point, ...]]]:
    out = {m: set() for m in range(4, max_len + 1, 2)}
    origin = (0, 0)

    def dfs(path: list[Point], target_len: int) -> None:
        current = path[-1]
        steps_used = len(path) - 1
        remaining = target_len - steps_used

        # Must be able to return to origin in the remaining steps.
        dist = abs(current[0]) + abs(current[1])
        if dist > remaining or (remaining - dist) % 2:
            return

        if steps_used == target_len:
            if current == origin:
                vertices = tuple(path[:-1])
                if len(set(vertices)) == target_len:
                    out[target_len].add(canonical_cycle(vertices))
            return

        for step in STEPS:
            nxt = add(current, step)
            if nxt == origin:
                if steps_used + 1 != target_len:
                    continue
            elif nxt in path:
                continue
            path.append(nxt)
            dfs(path, target_len)
            path.pop()

    for m in out:
        dfs([origin], m)
    return out


def cycle_stats(vertices: tuple[Point, ...]) -> tuple[int, int, int, int]:
    """Return m,n0,n1,ell on a large auxiliary torus."""
    m = len(vertices)
    n0 = n1 = 0
    horiz = []
    ys = [p[1] for p in vertices]

    for i, p in enumerate(vertices):
        q = vertices[(i + 1) % m]
        dx, dy = q[0] - p[0], q[1] - p[1]
        assert abs(dx) + abs(dy) == 1
        if dx:
            n0 += 1
            horiz.append((p[1], dx))
        else:
            n1 += 1

    assert n0 + n1 == m
    assert sum(dx for _, dx in horiz) == 0
    assert sum(
        vertices[(i + 1) % m][1] - vertices[i][1]
        for i in range(m)
    ) == 0

    # Embed without wrap in a torus with a long zero interval.
    ymin, ymax = min(ys), max(ys)
    span = ymax - ymin
    L = 2 * m + 4
    shift_y = m + 1 - ymin
    B = [0] * L
    for y, sign in horiz:
        B[y + shift_y] += sign
    assert sum(B) == 0

    H = [0] * L
    for r in range(1, L):
        H[r] = H[r - 1] + B[r]
    # Cyclic closure under the convention H(r)-H(r-1)=B(r):
    assert H[0] - H[-1] == B[0]

    median = sorted(H)[L // 2]
    ell = sum(abs(v - median) for v in H)

    # Additional internal witnesses used by the written proof.
    tv = sum(abs(v) for v in B)
    assert tv <= n0
    assert span <= n1 // 2
    assert max(H) - min(H) <= tv // 2 if tv % 2 == 0 else max(H) - min(H) <= Fraction(tv, 2)

    return m, n0, n1, ell


def cycle_audit() -> None:
    cycles = enumerate_simple_cycles(12)
    total = 0
    equality = 0
    counts = []

    for m in sorted(cycles):
        count = 0
        for cyc in cycles[m]:
            mm, n0, n1, ell = cycle_stats(cyc)
            assert mm == m
            assert 4 * ell <= n0 * n1
            assert 16 * ell <= m * m
            count += 1
            total += 1
            if 4 * ell == n0 * n1:
                equality += 1
        counts.append((m, count))

    assert total > 0
    print(
        "CYCLE_AUDIT PASS "
        f"total={total} equality_cases={equality} "
        + " ".join(f"m{m}={n}" for m, n in counts)
    )


def rectangle_cycle(a: int, b: int) -> tuple[Point, ...]:
    pts: list[Point] = []
    x = y = 0
    pts.append((x, y))
    for _ in range(a):
        x += 1
        pts.append((x, y))
    for _ in range(b):
        y += 1
        pts.append((x, y))
    for _ in range(a):
        x -= 1
        pts.append((x, y))
    for _ in range(b):
        y -= 1
        pts.append((x, y))
    assert pts[-1] == pts[0]
    return tuple(pts[:-1])


def rectangle_audit() -> None:
    count = 0
    for a, b in product(range(1, 7), repeat=2):
        cyc = rectangle_cycle(a, b)
        m, n0, n1, ell = cycle_stats(cyc)
        assert m == 2 * (a + b)
        assert n0 == 2 * a
        assert n1 == 2 * b
        assert ell == a * b
        assert 4 * ell == n0 * n1
        count += 1
    print(f"RECTANGLES PASS count={count} exact_ell_equals_area")


def bound_audit(A: Fraction, q: Fraction, A0: Fraction, q0: Fraction) -> tuple[Fraction, Fraction]:
    c12 = A * S3(q) / 64
    c0 = A0 * S3(q0) / 64
    assert c12 > 0 and c0 > 0
    assert c0 < c12
    print(f"BOUND_CONTACT12 PASS C12={c12}")
    print(f"BOUND_CONTACT0 PASS C0={c0}")
    print(f"BOUND_DIGITS C12_num={len(str(c12.numerator))} C12_den={len(str(c12.denominator))} C0_num={len(str(c0.numerator))} C0_den={len(str(c0.denominator))}")
    return c12, c0


def main() -> None:
    A, q, A0, q0 = primitive_constants()
    series_identity_audit(q)
    series_identity_audit(q0)
    cycle_audit()
    rectangle_audit()
    bound_audit(A, q, A0, q0)
    print("AUDIT PASS; signed_single_cycle_uniform=YES; full_Xi=OPEN; P1=OPEN")


if __name__ == "__main__":
    main()
