#!/usr/bin/env python3
# C-GOLDEN-AME-TWOPLACE-1-N -- INDEPENDENT second derivation of the G3/G4
# decisive falsifier, written without reusing any code or intermediate data
# from the primary run (commit 177f2602). Input is only the pinned source
# AME46_ORIGINAL.m; claimed reference values from RESULT.md are re-derived
# here and compared explicitly.
#
# Checks, in order:
#   1. per-leg support degree vectors d_q
#   2. equal-degree class structure, max class sizes, degree-preserving
#      group orders
#   3. every order-5 element of S6 is a (5,1) cycle (full enumeration)
#   4. A5 is generated by its order-5 elements (orbit closure) and
#      5 does not divide |S4|, so every homomorphism A5 -> S4 is trivial
#   5. THE KILLER: no leg has an equal-degree class of size >= 5, so no
#      degree-preserving local 5-cycle exists on any leg
#   6. independent sweep of ALL degree-preserving identity-leg local
#      permutation tuples: support+letter survivors
#   7. exact mu_40 phase-lift test for each nontrivial survivor
#      (solvability mod 5 and mod 8; Z/40 by CRT)
#   8. independent sweep of all 720*24 strict simultaneous permutations
#      with tensor-leg permutations
#
# stdout is deterministic and byte-comparable across platforms.
#
# Usage: python3 review_g3_g4_independent.py --source AME46_ORIGINAL.m

import argparse
import hashlib
import itertools
import sys

PIN_M_SHA256 = "55fbc0ba2747b4e5adc5a5abd15ac7241a461ff8182268ebdae464d8a29cc9ae"
PIN_M_BYTES = 8515

# reference values claimed by RESULT.md (commit 177f2602), re-derived here
CLAIMED_DEG = {
    0: (20, 18, 16, 24, 16, 18),
    1: (14, 14, 22, 20, 20, 22),
    2: (20, 20, 18, 18, 18, 18),
    3: (18, 18, 18, 18, 20, 20),
}
CLAIMED_MAX_CLASSES = (2, 2, 4, 4)
CLAIMED_GROUP_ORDERS = (4, 8, 48, 48)

FAILURES = []


def report(line):
    sys.stdout.write(line + "\n")


def check(label, ok):
    report("%s : %s" % (label, "PASS" if ok else "FAIL"))
    if not ok:
        FAILURES.append(label)
    return ok


def parse_m(text):
    i0 = text.index("U = [")
    i1 = text.index("] .* w.^[", i0)
    i2 = text.index("];", i1 + 9)

    def rows_of(block, allowed):
        rows = []
        for raw in block.split(";"):
            toks = raw.replace(",", " ").split()
            if not toks:
                continue
            assert len(toks) == 36 and all(t in allowed for t in toks)
            rows.append(toks)
        assert len(rows) == 36
        return rows

    amp = rows_of(text[i0 + 5:i1], {"0", "a", "b", "c"})
    expo = rows_of(text[i1 + 9:i2], {str(k) for k in range(20)})
    return amp, [[int(t) for t in row] for row in expo]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True)
    args = ap.parse_args()
    sys.stderr.write("platform: %s %s\n" % (sys.platform, sys.version.replace("\n", " ")))

    report("C-GOLDEN-AME-TWOPLACE-1-N independent G3/G4 review")
    report("re-derives the decisive falsifier from the pinned source only")
    report("")

    data = open(args.source, "rb").read()
    if not check("pinned source bytes 8515 and sha256",
                 len(data) == PIN_M_BYTES
                 and hashlib.sha256(data).hexdigest() == PIN_M_SHA256):
        sys.exit(2)
    amp, expo = parse_m(data.decode("ascii"))

    # tensor support with letter and zeta_20-exponent, A[i,j,k,l]=U[6i+j,6k+l]
    S = {}
    for r in range(36):
        for cc in range(36):
            if amp[r][cc] != "0":
                x = (r // 6, r % 6, cc // 6, cc % 6)
                S[x] = (amp[r][cc], expo[r][cc])
    check("support size 112", len(S) == 112)

    report("")
    report("-- 1. per-leg support degree vectors d_q(r) = #{x in S : x_q = r} --")
    deg = {}
    for q in range(4):
        d = [0] * 6
        for x in S:
            d[x[q]] += 1
        deg[q] = tuple(d)
        report("leg %d : %s" % (q, str(deg[q])))
        check("leg %d degree vector equals RESULT.md claim %s"
              % (q, str(CLAIMED_DEG[q])), deg[q] == CLAIMED_DEG[q])
    check("degree sum on every leg is 112", all(sum(deg[q]) == 112 for q in range(4)))

    report("")
    report("-- 2. equal-degree classes and degree-preserving groups --")
    max_classes = []
    group_orders = []
    classes_by_leg = []
    for q in range(4):
        cls = {}
        for r in range(6):
            cls.setdefault(deg[q][r], []).append(r)
        classes = sorted((v, sorted(rs)) for v, rs in cls.items())
        classes_by_leg.append([rs for _, rs in classes])
        mx = max(len(rs) for _, rs in classes)
        order = 1
        for _, rs in classes:
            f = 1
            for n in range(2, len(rs) + 1):
                f *= n
            order *= f
        max_classes.append(mx)
        group_orders.append(order)
        report("leg %d classes: %s ; max class %d ; degree-preserving group order %d"
               % (q, str(classes), mx, order))
    check("max equal-degree classes = %s" % str(CLAIMED_MAX_CLASSES),
          tuple(max_classes) == CLAIMED_MAX_CLASSES)
    check("degree-preserving group orders = %s" % str(CLAIMED_GROUP_ORDERS),
          tuple(group_orders) == CLAIMED_GROUP_ORDERS)

    report("")
    report("-- 3. order-5 elements of S6 --")
    n5 = 0
    all51 = True
    for p in itertools.permutations(range(6)):
        # order of permutation
        seen = [False] * 6
        lens = []
        for st in range(6):
            if not seen[st]:
                ln = 0
                cur = st
                while not seen[cur]:
                    seen[cur] = True
                    cur = p[cur]
                    ln += 1
                lens.append(ln)
        lcm = 1
        for ln in lens:
            g = lcm
            a, b = lcm, ln
            while b:
                a, b = b, a % b
            lcm = g * ln // a
        if lcm == 5:
            n5 += 1
            if sorted(lens) != [1, 5]:
                all51 = False
    report("elements of order 5 in S6: %d" % n5)
    check("every order-5 element of S6 has cycle type (5,1)", all51 and n5 == 144)

    report("")
    report("-- 4. homomorphisms A5 -> S4 are trivial --")
    report("|S4| = 24 and 5 does not divide 24, so every order-5 element maps to id")
    # A5 as even permutations of 5 points; generate from its 5-cycles
    a5 = set()
    fives = []
    for p in itertools.permutations(range(5)):
        # parity
        inv = sum(1 for i in range(5) for j in range(i + 1, 5) if p[i] > p[j])
        if inv % 2 == 0:
            a5.add(p)
    for p in a5:
        seen = [False] * 5
        lens = []
        for st in range(5):
            if not seen[st]:
                ln = 0
                cur = st
                while not seen[cur]:
                    seen[cur] = True
                    cur = p[cur]
                    ln += 1
                lens.append(ln)
        if sorted(lens) == [5]:
            fives.append(p)
    gen = {tuple(range(5))}
    frontier = [tuple(range(5))]
    while frontier:
        nxt = []
        for g in frontier:
            for f in fives:
                h = tuple(g[f[i]] for i in range(5))
                if h not in gen:
                    gen.add(h)
                    nxt.append(h)
        frontier = nxt
    check("A5 (order 60) is generated by its %d five-cycles" % len(fives),
          len(gen) == 60 and len(a5) == 60)
    report("hence any homomorphism A5 -> S4 kills the 5-cycles and so all of A5;")
    report("every tensor-leg permutation attached to an A5 action is the identity")

    report("")
    report("-- 5. THE KILLER --")
    report("a faithful six-point A5 action contains an order-5 element; on six")
    report("points it acts as a (5,1) cycle (step 3); with identity leg permutation")
    report("(step 4) a local monomial symmetry maps support bijectively to support,")
    report("so its local permutation preserves d_q; a 5-cycle then needs an")
    report("equal-degree class of size >= 5 on that leg")
    killer = all(mx < 5 for mx in max_classes)
    check("no leg has an equal-degree class of size >= 5 (max = %s)"
          % str(tuple(max_classes)), killer)
    check("G4 falsifier CONFIRMED independently: no faithful diagonal A5 in the frozen monomial class",
          killer)

    report("")
    report("-- 6. independent sweep: identity-leg degree-preserving tuples --")
    # all per-leg permutations preserving the degree vector, as products over classes
    def leg_perms(q):
        out = []
        classes = classes_by_leg[q]
        pools = [list(itertools.permutations(rs)) for rs in classes]
        for combo in itertools.product(*pools):
            p = [None] * 6
            for rs, im in zip(classes, combo):
                for src, dst in zip(rs, im):
                    p[src] = dst
            out.append(tuple(p))
        return out

    LP = [leg_perms(q) for q in range(4)]
    total = 1
    for q in range(4):
        total *= len(LP[q])
    report("tuple count = %d * %d * %d * %d = %d"
           % (len(LP[0]), len(LP[1]), len(LP[2]), len(LP[3]), total))
    check("tuple count equals 73728", total == 73728)

    Sset = frozenset(S.keys())
    survivors = []
    for p0 in LP[0]:
        for p1 in LP[1]:
            # prefilter on the (leg0, leg1) marginal support
            ok01 = True
            m01 = {}
            for x in S:
                m01[(x[0], x[1])] = m01.get((x[0], x[1]), 0) + 1
            for (r0, r1), cnt in m01.items():
                if m01.get((p0[r0], p1[r1]), 0) != cnt:
                    ok01 = False
                    break
            if not ok01:
                continue
            for p2 in LP[2]:
                for p3 in LP[3]:
                    good = True
                    for x in S:
                        y = (p0[x[0]], p1[x[1]], p2[x[2]], p3[x[3]])
                        if y not in Sset or S[y][0] != S[x][0]:
                            good = False
                            break
                    if good:
                        survivors.append((p0, p1, p2, p3))
    report("support+letter survivors: %d" % len(survivors))
    ident = tuple(range(6))
    swap = (1, 0, 3, 2, 5, 4)  # (01)(23)(45)
    named = []
    for sv in survivors:
        tag = []
        for q in range(4):
            if sv[q] == ident:
                tag.append("id")
            elif sv[q] == swap:
                tag.append("(01)(23)(45)")
            else:
                tag.append(str(sv[q]))
        named.append("(" + ",".join(tag) + ")")
    for nm in sorted(named):
        report("  survivor: %s" % nm)
    check("survivors are exactly identity and (id,id,(01)(23)(45),(01)(23)(45))",
          sorted(named) == sorted(["(id,id,id,id)",
                                   "(id,id,(01)(23)(45),(01)(23)(45))"]))

    report("")
    report("-- 7. exact mu_40 phase lift for nontrivial survivors --")
    report("equation per support point x, unknowns delta_q(r) (24) and chi (1) in Z/40:")
    report("  sum_q delta_q(rho_q(x_q)) + 2 e(x) - 2 e(rho(x)) = chi  (mod 40)")
    report("solvable over Z/40 iff solvable mod 5 and mod 8 (CRT)")

    def phase_solvable(sv, mod):
        # unknowns: delta[q][r] -> index 6q+r (24), chi -> index 24
        rows = []
        for x in S:
            y = tuple(sv[q][x[q]] for q in range(4))
            vec = [0] * 25
            for q in range(4):
                vec[6 * q + y[q]] += 1
            vec[24] -= 1
            rhs = (2 * S[y][1] - 2 * S[x][1]) % mod
            rows.append(([v % mod for v in vec], rhs))
        # Gaussian elimination mod `mod` (pivots restricted to units)
        ncols = 25
        pivots = 0
        for col in range(ncols):
            piv = None
            for ri in range(pivots, len(rows)):
                a = rows[ri][0][col] % mod
                if a != 0 and (mod == 5 or a % 2 == 1):
                    piv = ri
                    break
            if piv is None:
                continue
            rows[pivots], rows[piv] = rows[piv], rows[pivots]
            vec, rhs = rows[pivots]
            inv = pow(vec[col], -1, mod)
            vec = [(v * inv) % mod for v in vec]
            rhs = (rhs * inv) % mod
            rows[pivots] = (vec, rhs)
            for ri in range(len(rows)):
                if ri != pivots and rows[ri][0][col] % mod != 0:
                    f = rows[ri][0][col] % mod
                    nv = [(a - f * b) % mod for a, b in zip(rows[ri][0], vec)]
                    nr = (rows[ri][1] - f * rhs) % mod
                    rows[ri] = (nv, nr)
            pivots += 1
        insol = [(v, r) for (v, r) in rows if all(a % mod == 0 for a in v) and r % mod != 0]
        return (len(insol) == 0), pivots, len(insol)

    for sv, nm in zip(survivors, named):
        if all(sv[q] == ident for q in range(4)):
            continue
        s5, rank5, bad5 = phase_solvable(sv, 5)
        s8, rank8, bad8 = phase_solvable(sv, 8)
        report("survivor %s :" % nm)
        report("  mod 5: rank %d, inconsistent rows %d -> %s"
               % (rank5, bad5, "solvable" if s5 else "UNSOLVABLE (field elimination, certified)"))
        report("  mod 8: rank %d, inconsistent rows %d -> %s"
               % (rank8, bad8, "no unit-pivot obstruction" if s8 else "UNSOLVABLE"))
        check("survivor %s has NO mu_40 phase lift" % nm, not (s5 and s8))

    report("")
    report("-- 8. strict simultaneous sweep: 720 sigma x 24 leg permutations --")
    strict_comb = 0
    strict_full = 0
    for sig in itertools.permutations(range(6)):
        for legp in itertools.permutations(range(4)):
            good = True
            for x in S:
                xp = tuple(x[legp[q]] for q in range(4))
                y = tuple(sig[xp[q]] for q in range(4))
                if y not in Sset or S[y][0] != S[x][0]:
                    good = False
                    break
            if good:
                strict_comb += 1
                sv4 = (sig, sig, sig, sig)
                if all(x == y for x, y in zip(legp, range(4))):
                    s5, _, _ = phase_solvable(sv4, 5)
                    s8, _, _ = phase_solvable(sv4, 8)
                    if s5 and s8:
                        strict_full += 1
                else:
                    # leg-permuted case: combinatorial survivor recorded;
                    # phase test in the permuted convention
                    strict_full += 0
                if not (sig == ident and tuple(legp) == (0, 1, 2, 3)):
                    report("  strict combinatorial survivor: sigma=%s legs=%s"
                           % (str(sig), str(legp)))
    report("strict combinatorial survivors: %d" % strict_comb)
    check("only the identity survives the strict simultaneous sweep even combinatorially",
          strict_comb == 1)
    check("strict projective stabilizer is trivial", strict_full == 1)

    report("")
    report("== REVIEW VERDICT ==")
    if FAILURES:
        report("INDEPENDENT G3/G4 REVIEW: FAIL (%d)" % len(FAILURES))
        for f in FAILURES:
            report("  FAILED: %s" % f)
        sys.exit(1)
    report("INDEPENDENT G3/G4 REVIEW: CONFIRMED")
    report("the preregistered G4 hard falsifier fires: no faithful six-point A5")
    report("action exists in the frozen local monomial class of the pinned tensor;")
    report("degree vectors, class sizes, survivor list, and the phase obstruction")
    report("of RESULT.md commit 177f2602 are all re-derived independently")


if __name__ == "__main__":
    main()
